# Generated by Django 3.1.2 on 2020-10-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Стадіон')),
                ('lighting', models.BooleanField(verbose_name='Освітлення')),
                ('shower', models.BooleanField(verbose_name='Душ')),
                ('section', models.BooleanField(verbose_name='Роздівалки')),
                ('parking', models.BooleanField(verbose_name='Парковка')),
                ('address', models.CharField(max_length=100, verbose_name='Адреса')),
                ('size', models.CharField(max_length=100, verbose_name='Розмір')),
            ],
            options={
                'verbose_name': 'Стадіон',
                'verbose_name_plural': 'Стадіони',
                'ordering': ['name'],
            },
        ),
    ]
