# Generated by Django 3.1.2 on 2020-10-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coverage', '0002_auto_20201028_1022'),
        ('cities', '0001_initial'),
        ('type_st', '0001_initial'),
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='city', to='cities.city', verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='field',
            name='coverage',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='coverage', to='coverage.coverage', verbose_name='Покриття'),
        ),
        migrations.AddField(
            model_name='field',
            name='type',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, related_name='type', to='type_st.type', verbose_name='Тип поля'),
        ),
    ]
